### PR TITLE
Footer and icons' path improvement

### LINKED ISSUE #2: Add link for our GitHub to footer

### PR DESCRIPTION
**Pull request by lukynmatuska**
- Added GitHub icon and link to footer
- Add YouTube icon and link to footer on some pages where were missing

### CODE REVIEW

**Comment by lukynmatuska** [comment]
This PR will fix #2.

**Comment by lukynmatuska** [comment]
Fixes #2.

**Comment by lukynmatuska** [comment]
Screenshot_2022-11-29-21-53-08-31_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by lukynmatuska** [comment]
Screenshot_2022-11-29-21-59-42-94_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by lukynmatuska** [comment]
Fixes #4.

**Comment by ondryaso** [comment]
Fixed in 749d43c.

**Pull request closed without merging**
